module.exports = {
    login: {
        scripts: [
            '/assets/cdn/jquery/jquery.js',
            '/assets/cdn/bootstrap/js/bootstrap.js',
            '/assets/cdn/client/client.js',
            '/assets/cdn/sweetalert2/sweetalert2.min.js',
            '/assets/cdn/select2/js/select2.full.min.js',
            '/assets/cdn/moment/moment.min.js',
            '/assets/cdn/popper/umd/popper.min.js',
            '/assets/cdn/summernote/summernote-bs4.js',
            '/assets/cdn/datatables/jquery.dataTables.min.js',
            '/assets/cdn/datatables-bs4/js/dataTables.bootstrap4.min.js',
            '/assets/cdn/datatables-responsive/js/dataTables.responsive.min.js',
            '/assets/cdn/datatables-responsive/js/responsive.bootstrap4.min.js',
            '/assets/cdn/voca/voca.js',
            '/assets/cdn/holdon/holdOn.js',
            //'/assets/cdn/neumorphism/neumorphism.js',
        ],
        styles: [
            '/assets/cdn/bootstrap/css/bootstrap.css',
            '/assets/cdn/animate/animate.css',
            '/assets/cdn/fontawesome-free/css/all.min.css',
            '/assets/cdn/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css',
            '/assets/cdn/select2/css/select2.min.css',
            '/assets/cdn/select2-bootstrap4-theme/select2-bootstrap4.min.css',
            '/assets/cdn/summernote/summernote-bs4.css',
            '/assets/cdn/datatables-bs4/css/dataTables.bootstrap4.min.css',
            '/assets/cdn/datatables-responsive/css/responsive.bootstrap4.min.css',
            '/assets/cdn/holdon/holdOn.css',
            '/assets/cdn/neumorphism/neumorphism.css',

        ],
    },
    cp: {
        scripts: [
            '/assets/cdn/jquery/jquery.js',
            '/assets/cdn/bootstrap/js/bootstrap.js',
            '/assets/cdn/client/client.js',
            '/assets/cdn/sweetalert2/sweetalert2.min.js',
            '/assets/cdn/select2/js/select2.full.min.js',
            '/assets/cdn/moment/moment.min.js',
            '/assets/cdn/popper/umd/popper.min.js',
            '/assets/cdn/summernote/summernote-bs4.js',
            '/assets/cdn/datatables/jquery.dataTables.min.js',
            '/assets/cdn/datatables-bs4/js/dataTables.bootstrap4.min.js',
            '/assets/cdn/datatables-responsive/js/dataTables.responsive.min.js',
            '/assets/cdn/datatables-responsive/js/responsive.bootstrap4.min.js',
            '/assets/cdn/voca/voca.js',
            '/assets/cdn/holdon/holdOn.js',
            //'/assets/cdn/neumorphism/neumorphism.js',
        ],
        styles: [
            '/assets/cdn/bootstrap/css/bootstrap.css',
            '/assets/cdn/animate/animate.css',
            '/assets/cdn/fontawesome-free/css/all.min.css',
            '/assets/cdn/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css',
            '/assets/cdn/select2/css/select2.min.css',
            '/assets/cdn/select2-bootstrap4-theme/select2-bootstrap4.min.css',
            '/assets/cdn/summernote/summernote-bs4.css',
            '/assets/cdn/datatables-bs4/css/dataTables.bootstrap4.min.css',
            '/assets/cdn/datatables-responsive/css/responsive.bootstrap4.min.css',
            '/assets/cdn/holdon/holdOn.css',
            '/assets/cdn/photon/css/photon.css',

        ],
    },
}